version: '3.8'

services:
  simplyfund-api:
    container_name: simplyfund-api
    build:
      context: .
      dockerfile: Simplyfund.Api/Dockerfile
    ports:
      - "8082:8080"
      # - "4443:4443"
    # networks:
    #   - simplyfund-net
    # volumes:
    #   - simplyfund-api-data:/volumen/

    # env_file: 
    #   - .env
    # environment:
    #   - userdb=simplyfund
    #   - passworddb=simplyfund
    #   - hostdb=simplyfunddb
    #   - ENVIROMENT=

  simplyfund-auth:
    container_name: simplyfund-auth
    build:
      context: .
      dockerfile: SimplyFund.Auth/Dockerfile
    ports:
      - "8083:8080"
      # - "4443:4443"
  #   networks:
  #     - simplyfund-net

  simplyfund-api-gateway:
    container_name: simplyfund-api-gateway
    build:
      context: .
      dockerfile: SimplyFund.ApiGateWay/Dockerfile
    ports:
      - "8084:8080"
      # - "4443:4443"
  #   networks:
  #     - simplyfund-net

  
  simplyfund-file:
    container_name: simplyfund-file
    build:
      context: .
      dockerfile: SimplyFund.File/Dockerfile
    ports:
      - "8085:8080"
      
  simplyfund-mail:
    container_name: simplyfund-mail
    build:
      context: .
      dockerfile: SimplyFund.Mail/Dockerfile
    ports:
      - "8086:8080"

# volumes:
#   simplyfund-api-data:
#     driver: local

# networks:
#     simplyfund-net:
#       name: simplyfund-net
